config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :accounts, controllers: {
    omniauth_callbacks: 'accounts/omniauth_callbacks'
  }
  root to: 'front/communities#show'

  scope module: 'front' do
    resources :channels, only: %i(show new create edit update)
    resources :places, only: %i(show new create edit update) do
      resources :notes, only: %i(new create edit update destroy)
      resource :copy, only: %i(new create)
    end
    resource :draft, only: %i(new create)
  end
end

app/views/shared/organisms/_header.slim
- back_path ||= nil

header.section.o-header
  .container.o-header__block
    - if back_path.present?
      = link_to back_path, class: 'o-header__link'
        span
          i.far.fa-arrow-alt-circle-left
    - else
      div

    = link_to root_path
      h1.o-header__title Cocchi

    div

app/views/shared/organisms/_nav.slim
- route_path ||= nil
- copy_path ||= nil
- order_path ||= nil

nav.section.o-nav.o-nav--icons
  .container
    .o-nav__block
      - if route_path
        = link_to route_path, class: 'o-nav__tab o-nav__tab--active', target: :_blank
          i.fas.fa-map-marker-alt.o-nav__icon
          span.o-nav__label Route
      - else
        .o-nav__tab
          i.fas.fa-map-marker-alt.o-nav__icon
          span.o-nav__label Route
      - if copy_path
        = link_to copy_path, class: 'o-nav__tab o-nav__tab--active'
          i.far.fa-copy.o-nav__icon
          span.o-nav__label Copy
      - else
        .o-nav__tab
          i.far.fa-copy.o-nav__icon
          span.o-nav__label Copy
      - if order_path
        = link_to order_path, class: 'o-nav__tab o-nav__tab--active', target: :_blank
          i.fas.fa-shopping-cart.o-nav__icon
          span.o-nav__label Order
      - else
        .o-nav__tab
          i.fas.fa-shopping-cart.o-nav__icon
          span.o-nav__label Order